-- MySQL Script generated by MySQL Workbench
-- Sun Mar 24 00:34:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema greencube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema greencube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `greencube` DEFAULT CHARACTER SET utf8 ;
USE `greencube` ;

-- -----------------------------------------------------
-- Table `greencube`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`User` (
  `id` INT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `oldPassword` VARCHAR(45) NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `salt` VARCHAR(45) NOT NULL,
  `roles` VARCHAR(45) NOT NULL DEFAULT '[\"ROLE_USER\"]',
  `enabled` TINYINT NOT NULL DEFAULT 0,
  `banned` TINYINT NOT NULL DEFAULT 0,
  `url` VARCHAR(45) NULL,
  `lastIp` VARCHAR(45) NOT NULL,
  `currency` VARCHAR(45) NOT NULL DEFAULT 'EUR',
  `lastLogin` DATETIME NULL,
  `locale` VARCHAR(45) NOT NULL DEFAULT 'fr',
  `confirmationToken` VARCHAR(45) NOT NULL,
  `bio` TEXT NULL,
  `birthday` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`PlantCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`PlantCategory` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`Country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `alpha2` VARCHAR(45) NOT NULL,
  `alpha3` VARCHAR(45) NOT NULL,
  `englishName` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`City` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zip` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `id_country` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `houseNumber` VARCHAR(45) NOT NULL,
  `id_city` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`Field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`Field` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_address` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`Cube`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`Cube` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `reference` VARCHAR(45) NOT NULL,
  `id_field` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`Seedling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`Seedling` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sownAt` DATETIME NOT NULL,
  `harvestDate` DATETIME NULL,
  `zone` VARCHAR(45) NULL,
  `id_cube` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`Vendor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`SensorCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`SensorCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `id_parent` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`SensorModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`SensorModel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `id_vendor` INT NULL,
  `id_category` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`Sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`Sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(45) NOT NULL,
  `id_model` INT NOT NULL,
  `id_cube` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`SeedlingSettings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`SeedlingSettings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`seedling_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`seedling_settings` (
  `id_seedling` INT NOT NULL,
  `id_seedling_settings` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id_seedling`, `id_seedling_settings`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`ExchangeItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`ExchangeItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL COMMENT 'Donner ou recevoir',
  `quantity` INT UNSIGNED NULL,
  `id_plant_category` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greencube`.`Annoucement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greencube`.`Annoucement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `id_giveaway` INT NULL,
  `id_takeaway` INT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
